POST http://127.0.0.1:5000/user/registration HTTP/1.1
content-type: application/json

{
  "login": "princess_julia",
  "key": "princess_julia",
  "email": "princess_julia",
  "name": "princess_julia"
}

###

GET http://jusrager.pythonanywhere.com/spells HTTP/1.1
